[package]
name = "slang-slim"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
description = "Safe Rust bindings for the focused slang-slim shader compiler"
license = "MIT"
repository = "https://github.com/ukabuer/rusty_slang_slim"
readme = "../../README.md"

[features]
default = ["native"]
native = ["slang-slim-sys/native"]

[package.metadata.docs.rs]
no-default-features = true

[dependencies]
slang-slim-sys = { path = "../slang-slim-sys", version = "0.1.1", default-features = false }
